---
- name: Setup NOE files
  import_tasks: "./setup_files.yml"

- name: Ensure ~/source exists
  file:
    path: "{{ home_dir }}/source"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  when: copy_source

- name: Copy in pom.xml
  copy:
    src: "{{ role_path }}/../../../pom.xml"
    dest: "{{ home_dir }}/source/pom.xml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  when: copy_source

- name: Copy in nifi_processors source
  copy:
    src: "{{ role_path }}/../../../nifi_processors"
    dest: "{{ home_dir }}/source"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  when: copy_source

- name: Remove target from copied source if there
  shell: "rm -rf {{ home_dir }}/source/nifi_processors/target || true"
  when: copy_source

- name: Install maven dependencies - offline
  import_tasks: "./offline-maven.yml"
  when: is_offline

- name: Get NiFi credentials
  import_tasks: "./nifi-creds.yml"

- name: Upload NOE template to NiFi
  import_tasks: "./upload-template.yml"
