---
- name: Remove all repos to make sure they are not enabled - offline
  shell: rm -rf /etc/yum.repos.d/*
  become: true
  when: is_offline and offline_yum_repo_location != ''

- name: Download offline repo - offline
  get_url:
    url: "{{ offline_yum_repo_location }}"
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    force: true # always download to make sure its enabled
  become: true
  when: >-
    is_offline
    and (
      offline_yum_repo_location is regex('^https:.*')
      or offline_yum_repo_location is regex('^http:.*')
    )

- name: Copy offline repo - offline
  copy:
    src: "{{ offline_yum_repo_location.replace('remote:', '').replace('local:', '') }}"
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    remote_src: "{{ true if offline_yum_repo_location is regex('^remote:.*') else false | bool }}"
    force: true # always copy to make sure its enabled
  become: true
  when: >-
    is_offline
    and (
      offline_yum_repo_location is regex('^remote:.*')
      or offline_yum_repo_location is regex('^local:.*')
    )

- name: DNF Update Cache
  dnf:
    update_cache: true
    state: latest
  become: true

- name: DNF Update
  dnf:
    name: "*"
    state: latest
  become: true

- name: Install packages
  import_tasks: "./packages.yml"

- name: Configure Java
  import_tasks: "./java.yml"

- name: Configure NiFi
  import_tasks: "./nifi.yml"

- name: Copy moretools Install Script
  copy:
    src: "{{ role_path }}/files/moretools.sh"
    dest: "{{ home_dir }}"
    mode: 0755
    owner: vagrant
    group: vagrant
  become: true

- name: Run moretools install script
  shell: "{{ home_dir }}/moretools.sh"
  become: true

- name: Set DISPLAY value for x-server - windows/linux
  lineinfile:
    path: "{{ home_dir }}/.bashrc"
    insertafter: EOF
    line: 'export DISPLAY="10.0.2.2:0.0"'
    state: present
  when: not is_macos

- name: Set DISPLAY value for x-server - macos
  lineinfile:
    path: "{{ home_dir }}/.bashrc"
    insertafter: EOF
    line: 'export DISPLAY="localhost:10.0"'
    state: present
  when: is_macos

- name: Source .bashrc file
  shell: "source {{ home_dir }}/.bashrc"

- name: Ensure {{ home_dir }}/source exists
  file:
    path: "{{ home_dir }}/source"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  when: copy_source

- name: Copy in pom.xml
  copy:
    src: "{{ role_path }}/../../../pom.xml"
    dest: "{{ home_dir }}/source/pom.xml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  when: copy_source

- name: Copy in nifi_processors source
  copy:
    src: "{{ role_path }}/../../../nifi_processors"
    dest: "{{ home_dir }}/source"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  when: copy_source

- name: Remove target from copied source if there
  shell: "rm -rf {{ home_dir }}/source/nifi_processors/target || true"
  when: copy_source

- name: Install maven dependencies - offline
  import_tasks: "./offline-maven.yml"
  when: is_offline

- name: Upload NOE template to NiFi
  import_tasks: "./upload-template.yml"
