---
- name: Install development tools
  dnf:
    name:
      - libsecret-devel
      - cmake
      - make
      - gcc-c++
      - epel-release
      - ruby
      - hexedit
      - xorg-x11-xauth
      - mod_ssl
      - httpd
      - wget
      - zip
      - unzip
    state: present
  become: true

- name: Install Server with GUI, ensures VM has GUI - offline
  dnf:
    name: "@Server with GUI"
    state: present
  become: true
  when: is_offline

- name: Install Python & Pip
  dnf:
    name:
      - python3
      - python3-pip
    state: latest
  become: true

- name: Install MESA Drivers
  dnf:
    name:
      - mesa-dri-drivers
  become: true

- name: Install MESA graphics libraries
  dnf:
    name:
      - mesa-libGL
      - mesa-libEGL
      - xorg-x11-server-common
    state: latest
  become: true

- name: Install Firefox
  yum:
    name: firefox
    state: latest
  become: true

- name: Set Timezone
  timezone:
    name: America/New_York
  become: true

- name: Install Git
  dnf:
    name: git
    state: latest
  become: true
