---
- name: Ensure offline-files directory exists
  file:
    path: "{{ role_path }}/files/offline-files"
    state: directory
    mode: 0755

- name: Create bin folder
  file:
    path: "{{ role_path }}/files/offline-files/bin"
    state: directory
    mode: 0755

- name: Create pip-packages folder
  file:
    path: "{{ role_path }}/files/offline-files/pip-packages"
    state: directory
    mode: 0755

- name: Download maven files
  import_tasks: "./mvn.yml"

- name: Download NiFi files
  import_tasks: "./nifi.yml"

- name: Download Version mariadb client {{ mariadb_client_version }}
  get_url:
    url: "https://dlm.mariadb.com/2912798/Connectors/java/connector-java-{{ mariadb_client_version }}/mariadb-java-client-{{ mariadb_client_version }}.jar"
    dest: "{{ role_path }}/files/offline-files/mariadb-java-client-{{ mariadb_client_version }}.jar"
    mode: 0755

- name: Download terraform binary and providers
  import_tasks: "./terraform.yml"

- name: Download packer binary and plugins
  import_tasks: "./packer.yml"

- name: Download python pip packages
  import_tasks: "./pip.yml"

- name: Create zip of offline-files
  archive:
    path: "{{ role_path }}/files/offline-files"
    dest: "{{ role_path }}/files/offline-files-{{ ansible_date_time.date }}.zip"
    format: zip
    mode: 0755
