---
- name: Download mariadb client - online
  get_url:
    url: https://dlm.mariadb.com/2912798/Connectors/java/connector-java-{{ mariadb_client_version }}/mariadb-java-client-{{ mariadb_client_version }}.jar
    dest: /opt/nifi/nifi-{{ nifi.version }}/lib/mariadb-java-client-{{ mariadb_client_version }}.jar
    owner: nifi
    group: nifi
    mode: 0755
  become: true
  when: not is_offline

- name: Copy mariadb client - offline
  copy:
    src: "{{ role_path }}/../offline-download/files/offline-files/mariadb-java-client-{{ mariadb_client_version }}.jar"
    dest: "/opt/nifi/nifi-{{ nifi.version }}/lib/mariadb-java-client-{{ mariadb_client_version }}.jar"
    owner: nifi
    group: nifi
    mode: 0755
  become: true
  when: is_offline

- name: Install MariaDB
  dnf:
    name:
      - mariadb-server
    update_cache: true
    disable_gpg_check: true
  become: true

- name: Enable Servics and Start MariaDB
  systemd:
    daemon-reload: true
    name: mariadb
    state: started
    enabled: true
  become: true

- name: Copy database provisioning, reprovisioning, and stored procedure scripts to local machine
  copy:
    src: "{{ item }}"
    dest: /opt/nifi/db_scripts/
    mode: 0755
  with_items:
    - prov/secure_mysql.sh
    - prov/secure_mysql.sql
    - prov/create_db.sh
    - prov/create_db.sql
    - prov/delete_tables.sql
    - prov/delete_data.sql
    - prov/create_tables.sql
    - prov/add_auto_increment_to_tables.sql
    - prov/load_data.sql
  become: true

- name: Execute Secure MySQL Script
  shell: "/opt/nifi/db_scripts/secure_mysql.sh"
  become: true

- name: Execute Create Database Script
  shell: "/opt/nifi/db_scripts/create_db.sh"
  become: true
