name: Build
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build Processors NAR
    strategy:
      matrix:
        os: [macos-11, ubuntu-20.04, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build NAR
        run: mvn clean install -Dmaven.test.skip=true
        shell: bash
