name: Code Linting
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  java-lint:
    name: Java Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Check Java Lint - Checkstyle
        run: mvn validate

  yaml-ansible-lint:
    name: Ansible & Yaml Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Pip install ansible, ansible-lint and yamllint
        run: pip install ansible ansible-lint yamllint

      - name: ansible & yaml lint
        run: python3 -m ansiblelint provisioning
