name: Code Linting
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  java-lint:
    name: Java Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Check Java Lint - Checkstyle
        run: mvn validate

  yaml-ansible-lint:
    name: Ansible & Yaml Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Pip install ansible, ansible-lint and yamllint
        run: pip install ansible ansible-lint yamllint

      - name: ansible & yaml lint
        run: python3 -m ansiblelint provisioning

  packer-lint:
    name: Packer Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-packer@main

      - name: Lint main packer
        run: packer fmt -check .
        working-directory: packer

      - name: Lint os_pkrvars
        run: packer fmt -check os_pkrvars/*
        working-directory: packer

  terraform-lint:
    name: Terraform Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Lint
        run: terraform fmt -check **/*.{tf,tfvars}
        working-directory: terraform
